# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title-bold: Jeneser
title-normal: by Jekyll
email: 1668358930@qq.com
description: 我是一位不断学习不断成长的前端开发者.每天鼓励自己进步一点点
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jeneser.github.io" # the base hostname & protocol for your site
author: jeneser
street_address: 河南理工大学
city: 焦作
state: CN
zip_code: 454000
country: 河南省　焦作市　山阳区
phone: 18839130035

# Plugins
gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jemoji

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages" 
tiles-count: 6

# Social settings
500px_url: 
facebook_url: 
github_url: 
gitlab_url: https://gitlab.com/u/andrewbanchich
googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
pinterest_url: 
slack_url: 
twitter_url: https://twitter.com/andrewbanchich

# Build settings
markdown: kramdown

# Plugin: jekyll-seo-tag
twitter:
  username: andrewbanchich
# Add one or more of the following
facebook:
  app_id: 
  publisher: 
  admins: 
logo:
google_site_verification: 
